messagesLang: ru # Язык сообщений (ru, eu)

sleepTabStatus: true #Отображение в табе "Zz" после ника, если игрок спит
skipNight: #Настройки пропуска ночи
  enable: true #Включить(<true>) / Выключить(<false>)
  skipSpeed: 60 #Скорость скипа(Чтобы отключить скип, не нужно ставить скорость на 10000, просто включите instantSkip)
  sleepingPlayersThreshold: 0.5 # Порог спящих игроков для пропуска ночи (0.00 - 1.00). 0.5 - половина
  instantSkip: false # <true>, если хотите мнгновенный скип ночи, без анимации

chat: # Настройки чата
  enabled: true #Включить(<true>) / Выключить(<false>) расширенный чат
  local: true #Включить(<true>) / Выключить(<false>) локальный чат
  radius: 128 #Радиус локального чата

  globalFormat: "&7{chat_prefix} [{world_prefix}&7] ({player}&7) > {message}"
  localFormat: "&7{chat_prefix} {player} (<SOLID:afff69>{recipients}&7) > {message}"

  prefix: # Префиксы в чате
    # Пишет в глобальном чате в каком миру игрок
    worldPrefix:
      world: "World"
      color_world: "97cc99"

      world_nether: "Nether"
      color_world_nether: "cc9797"

      world_the_end: "End"
      color_world_the_end: "af97cc"

      # Добавте сюда префикс для своих миров если они есть
      # Пример:
      # otherWorld : "Мир 5"
      # color_otherWorld : "aabbcc"

    # Префикс обозначающий в какой чат написал игрок (глобальный, локальный)
    chatPrefix:
      global: "Ⓖ"
      local: "Ⓛ"

#Кастомный ТАБ
CustomTAB:
  #Включить кастомный таб
  enabled: true
  #Интервал обновления
  interval: 500
  #Верхняя часть таба
  header:
    - "<SOLID:00ffae>#LMPX"
    - "&7Пинг: {ping}&f &l&7TPS: {tps}"
    - ""
  #Нижняя часть таба
  footer:
    - ""
    - "&7Онлайн: <SOLID:fff082>{online}"
    - "&7ОЗУ: <SOLID:fff082>%server_ram_used%&7 / <SOLID:fff082>%server_ram_max% &7Чанков: <SOLID:fff082>%server_total_chunks% &7Сущностей: <SOLID:fff082>%server_total_entities%"
    - "&f{motd}"
  #Формат отображения игрока в табе
  playerFormat: "{player} {sleeping}"
  #Формат отображения статуса сна
  sleepStatus: "&7Zzz"

  # Настройки источника серверных сообщений
  # Для работы плейсхолдера {MOTD}, сервер должен возвращать text/plain
  # Если сервер не активен, то {MOTD} - пустая строка => выключено
  MOTDUrl: "http://localhost:1331/motd"
  MOTDUpdateInterval: 15000