messagesLang: ru # Язык сообщений (ru, eu)

sleepTabStatus: true #Отображение в табе "Zz" после ника, если игрок спит
skipNight: #Настройки пропуска ночи
  enable: true #Включить(<true>) / Выключить(<false>)
  skipSpeed: 60 #Скорость скипа(Чтобы отключить скип, не нужно ставить скорость на 10000, просто включите instantSkip)
  sleepingPlayersThreshold: 0.5 # Порог спящих игроков для пропуска ночи (0.00 - 1.00). 0.5 - половина
  instantSkip: false # <true>, если хотите мнгновенный скип ночи, без анимации

chat: # Настройки чата
  enabled: true #Включить(<true>) / Выключить(<false>) расширенный чат
  local: true #Включить(<true>) / Выключить(<false>) локальный чат
  radius: 128 #Радиус локального чата

  globalFormat: "&7{chat_prefix} [{world_prefix}&7] ({player}&7) > {message}"
  localFormat: "&7{chat_prefix} {player} (<SOLID:afff69>{recipients}&7) > {message}"

  prefix: # Префиксы в чате
    # Пишет в глобальном чате в каком миру игрок
    worldPrefix:
      world: "World"
      color_world: "97cc99"

      world_nether: "Nether"
      color_world_nether: "cc9797"

      world_the_end: "End"
      color_world_the_end: "af97cc"

      # Добавте сюда префикс для своих миров если они есть
      # Пример:
      # otherWorld : "Мир 5"
      # color_otherWorld : "aabbcc"

    # Префикс обозначающий в какой чат написал игрок (глобальный, локальный)
    chatPrefix:
      global: "Ⓖ"
      local: "Ⓛ"