name: Esx3
main: ru.lmpx.Esx3.Main
version: "1.0.2"
author: LIMPIX31
api-version: 1.16
description: server tools kit for server
softdepend:
  - PlaceholderAPI

commands:
  esx3:
    usage: /Esx3 [reload]
    description: management esx3 plugin

permissions:
  esx3.*:
    children:
      - esx3.esx3plugin
      - esx3.reloadPlugin