name: Esx3
main: ru.lmpx.Esx3.Main
version: "1.0.0"
author: LIMPIX31
api-version: 1.16
description: server tools kit for lmpx server
softdepend:
  - PlaceholderAPI

commands:
  lmpx:
    usage: /Esx3 [reload]
    description: management lmpx plugin
  sleepManager:
    usage: /sleepManager [speed]
    description: management skip night

permissions:
  esx3.*:
    children:
      - esx3.esx3plugin
      - esx3.reloadPlugin
      - esx3.sleepManager
      - esx3.sleepManagerEnable
      - esx3.sleepManagerSetSpeed